POST  http://localhost:3001/notes HTTP/1.1
Content-Type: application/json

 {
      "title": "Groceries",
      "content": "Eggs,Milk,Bread",
      "id": 100
}

###
PUT  http://localhost:3001/notes/3 HTTP/1.1
Content-Type: application/json

{
    "title": "The little prince",
    "content": "sdfsfsdfsdf"
}
